# Generated by Django 5.2.13 on 2026-05-13 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_user_is_super_admin_alter_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all discounts across bill items.', max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied = original_price - price (0 if no discount).', max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="The service's listed price at the time of billing.", max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave blank to make this service available to all branches (legacy). Set branch for branch-specific services.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The final (possibly edited) price charged to the customer.', max_digits=10),
        ),
    ]
